### ISSUE TITLE
What do we want to do with 4-digit FIPS?

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#1]
For some states lower in the alphabet (like Alabama), the state FIPS starts with a zero ("01"). Right now, those are showing up as four-digit FIPS from `get_county_cd`. Do we want to keep that, or do we want to use `sprintf` to pad with a leading zero?

It will depend in part on how later functions need to call these. For other county packages we're working on, we always pad with leading zeros to get to five digits.

**Comment by rodlammers** [comment]
Yes, we should pad it with a zero. That explains some of the problems I've
been having, thanks! I'm actually working on the package right now so I'll
modify the get_county_cd function.

**Comment by geanders** [comment]
Let me know if you have any problems with that. `sprintf` usually works great.

**Comment by rodlammers** [comment]
Yep, looks good! Right now I have the results being outputted by gage. I
know you are more interested in county-level outputs. I'm curious if have
any ideas for the types of metrics that would be beneficial for measuring
county-level flood impacts. Is it the # or % of gages that had a flood?
What flood magnitude are you most interested in (moderate, major, extreme)?

**Comment by rodlammers** [comment]
Sorry, maybe this should be put in its own "Issue."

**Comment by geanders** [comment]
I'm hoping you might have some good ideas for that... That will be the tricky part. I think to get to county, it probably makes sense to give both the % of gages in the county that had a flood and the number. That would let people do some sensitivity analysis. Same with flood magnitude. It would be great if we output assessments for a few levels, so users can chose themselves and also test results using different levels.

**Comment by geanders** [comment]
Yeah, we could move this to a new issue.

Also, would you go ahead and push your latest stuff to GitHub? I've been working some on documentation, but I'll wait to work more until later so we won't end up with loads of conflicts. If you push your stuff, I'll pull it in and fix any merge conflicts and then push up my latest stuff, then you can pull that and we won't end up with too many problems.

**Comment by rodlammers** [comment]
Sounds good, I'll push my latest work.

**Comment by geanders** [comment]
Great, let me know when you have.

**Comment by rodlammers** [comment]
Ok, I think it's all up there.

**Comment by geanders** [comment]
Great. There weren't any conflicts. I pushed my latest stuff up, so if you pull you'll have it all.

I'll wait a bit to dig in some more so we won't end up with loads of conflicts by working on it at the same time.

**Comment by rodlammers** [comment]
Sounds good. I'll work on it a bit more, push any changes I make, and let you know.

**Comment by rodlammers** [comment]
I just pushed my changes. I'll wait to edit again until I hear back from you about any edits/additions you made.
