### ISSUE TITLE
Do we need the full output for `find_nws`?

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#13]
When I changed `find_nws` to use `dplyr` functions, I ended up with a dataframe with just the `flood_val` and `site_no`. This means it's dropping all the other columns that were in the `NWS_flood_discharge` dataset. Do we need the other columns, or is this function really just trying to get the flood levels for a certain type for each site?

**Comment by rodlammers** [comment]
Those are the only two values we need so I think that should be fine.
