### ISSUE TITLE
Put data we want to use in `data` folder

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#2]
Right now, it looks like we're pulling data straight from `data-raw` to use. We'll want to write any data we want to include in the package to `data` (you can use the `use_data` function from `devtools`) if we want to use it in the package. (We can keep raw data and scripts in `data-raw`.)

**Comment by rodlammers** [comment]
The files in data-raw are just what I used to create the data that is used
in the package. The actual data is saved as system data (sysdata.rda) since
it doesn't need to be accessible by the user just by the internal package
functions. Is that the right way to go about this?

**Comment by geanders** [comment]
Hmm... I always just put it all in the `data` folder, whether the user will need to use it or not. I'm not sure if the `sysdata.rda` will pass CRAN checks.

**Comment by rodlammers** [comment]
I was going off Hadley Wickham's R packages book...

**Comment by geanders** [comment]
If Hadley suggested it, it's right :) Sounds great, I learned something.
