### ISSUE TITLE
Analysis using NWS flood thresholds

### ISSUE THREAD

**Issue by rodlammers** [rodlammers/countyfloods#22]
As the code is written know, if the NWS flood thresholds are used, a single value is chosen (from "action", "flood", "moderate", or "major"). This single value is then used to develop flood ratios which are then grouped into "none", "minor", "moderate", "major", or "extreme" based on their value. This approach is appropriate when using the Q2 value but may not be for the NWS thresholds. Because they are already divided into classes, would it make more sense to just say when the flow is above one of these classes? This gets a little tricky for "averaging" the flood magnitude across multiple days (e.g. what is the average of "flood", "moderate", and "major"?). Also, not all gages have all the NWS thresholds available (e.g. may only have "flood") which makes direct comparison between gages more difficult. 

Sorry this is a little rambling. Do you have any thoughts on this? Is the current approach OK or do you think we should try to change it?

**Comment by geanders** [comment]
> Because they are already divided into classes, would it make more sense to just say when the flow is above one of these classes? This gets a little tricky for "averaging" the flood magnitude across multiple days (e.g. what is the average of "flood", "moderate", and "major"?). 

I think this is on the right track-- maybe the right way to aggregate would be to give a measure of (1) at least one monitor in the county met or exceeded a certain category level over the time window and (2) half or more of the monitors in the county met or exceeded a certain category level over the time window. 

This might also help us decide-- how many monitors is it typical for a county to have? Is it usually very low (one or two), or are 10 or more common?

**Comment by rodlammers** [comment]
The number of monitors is more often low than high. But I think your aggregation approach is a good start. We might just have to include more metadata in the output to help clarify things for the user (e.g. if a flow exceeded the "flood" threshold but there were no higher NWS thresholds available for that gage).

**Comment by geanders** [comment]
Yes, I agree that including some meta-data about how many monitors the aggregation is based on would be very useful.

**Comment by rodlammers** [comment]
I've modified the code to just say if the flow is above the specified flood threshold. So the user still specifies a threshold (e.g. "action", "flood", etc.). The "flood" column of the gage level output is then either "flood" or "no flood". For county level, it outputs the percentage of gages with a flood and without a flood. The mapping has been similarly updated.
