### ISSUE TITLE
dplyr version of adply?

### ISSUE THREAD

**Issue by rodlammers** [rodlammers/countyfloods#23]
Hi Brooke,

I'm trying to figure out a dplyr version of adply (applying a function to each row of a dataframe). I have the following function:

```
  flood_analysis_loop <- function(flow_data, peaks, gages, county_cd, q2_val, start_date, end_date) {
    flow_data_new <- flow_data %>%
      dplyr::group_by_(~ site_no) %>%
      dplyr::filter_(~ date >= start_date & date <= end_date)

    flood_stats <- flood_analysis(flow_data = flow_data_new, peaks = peaks, gages = gages,
                                  county_cd = county_cd, q2_val = q2_val)

    return(flood_stats)
  }
```

I then want to apply this function to every row in `input_df`. Three inputs: `county_cd`, `start_date`, and `end_date` are the three columns of `input_df`. The rest of the function inputs are their own dataframes to be passed separately. I'm using the `rowwise` function but am having trouble getting the function to recognize the three inputs in `input_df`:

```
  flood_stats <- input_df %>%
    rowwise() %>%
    flood_analysis_loop(flow_data = flow_data,
                        peaks = peaks, gages = gages, q2_val = q2_val)
```

Do you have any advice? I'm not even sure how to combine the `input_df` inputs and external inputs using `adply`, let alone `rowwise`.

**Comment by geanders** [comment]
Will you have different data frames for `peaks` and `gages` for each row, or are those the same for all the rows you want to work through?

**Comment by geanders** [comment]
Also, is the output of `flood_analysis_loop` a dataframe, or a vector?

**Comment by geanders** [comment]
You may want to explore using `map` from the `purrr` package, rather than `dplyr` functions.

**Comment by rodlammers** [comment]
The data frames for `peaks` and `gages` will be the same for each row.

The output of `flood_analysis_loop` is a dataframe.

I'll look into `map`, thanks!

**Comment by rodlammers** [comment]
Also, I've started working on this issue as well as the time series function. I have to quit soon so I'll just comment out any non-functioning code before I push my new version to github.

**Comment by geanders** [comment]
Yeah, if it's going to be a dataframe, then I think you'll need `map`. 

> Also, I've started working on this issue as well as the time series function. I have to quit soon so I'll just comment out any non-functioning code before I push my new version to github.

Sounds great.

**Comment by rodlammers** [comment]
I ended up going with the `mdply` function from `plyr`. The `map` function doesn't seem to send the columns of the input data frame as inputs to the function. The `invoke_rows` function from `purrr` is promising but can only return a single row per row of the input data frame. Since we potentially need multiple rows (i.e. multiple gages per county per date range), this function doesn't work.
