### ISSUE TITLE
WISH: Add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [rodlammers/countyfloods#26]
Please consider adding:
```
URL: https://github.com/rodlammers/countyfloods
BugReports: https://github.com/rodlammers/countyfloods/issues
```
to this package's `DESCRIPTION` file to make it easier to find this GitHub repository from the CRAN package page.

**Comment by rodlammers** [comment]
I have added these lines to the `DESCRIPTION` file.  Thanks.
