### ISSUE TITLE
Explain warning message from `get_flow_data`

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#3]
In running the example for `get_flow_data`: 

```
miami_gages <- gage_extract("12086", start_date = "2000-01-01",
                            end_date = "2009-12-31")
miami_flow_data <- get_flow_data(site_no = miami_gages$site_no,
                                 start_date = "2000-01-01",
```

you get the following message: 

```
The following `from` values were not present in `x`: X_00060_00003
The following `from` values were not present in `x`: X_00060_00003
The following `from` values were not present in `x`: X_00060_00003
The following `from` values were not present in `x`: X_00060_00003
The following `from` values were not present in `x`: X_00060_00003
The following `from` values were not present in `x`: X_00060_00003
The following `from` values were not present in `x`: X_00060_00003
```

We need to explain this message in the documentation. Also, is it a message from our code, or from USGS functions? In either case, we might want to change or wrap the code to give a message that is easier to understand.

**Comment by rodlammers** [comment]
I'm honestly not sure what the error message is. It looks like it might be from the USGS function. I'll look into it.

**Comment by rodlammers** [comment]
Do you still get this error? It looks like this was from before you (and I) both changed this function. It also looks like you don't have an end date in the example above but that just might not have been pasted in.

**Comment by geanders** [comment]
No, you're right, I don't get this error anymore.
