### ISSUE TITLE
Clarify `get_flow_data` on common columns in output

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#4]
We probably need to add to the documentation for this function to explain columns like "X_PUBLISHED_00060_00003" and "X_PUBLISHED_00060_00003_cd".

**Comment by geanders** [comment]
Also, let's add the units for the Discharge measurement

**Comment by rodlammers** [comment]
Good catch, I can do that.

**Comment by geanders** [comment]
We might also think whether we want to keep all of these columns. If we're not using them for anything later, we might want to default to just include `date`, `discharge`, and `site_no`, and the user has to use a `complete = TRUE` option or something to pull all the possible columns.

**Comment by rodlammers** [comment]
There seems to be an issue when combining all the flow data from a list into a data frame. It looks like the USGS codes for the discharge measurements don't all have the same name so when you run `bind_rows` there are a bunch of columns all with different names. Then, only one column is renamed to "discharge" and carried forward. We need to somehow only keep the column without NAs for each site_no. I'll try to think up a simple way to do this.

**Comment by geanders** [comment]
Ahhh... okay. Do you know what the conventions are for the column names they have? Also, do we need to keep all those columns? If we just reduce down to a few that always show up (and with the same column names), I think it would resolve this.

**Comment by rodlammers** [comment]
The convention is generally "X_00060_00003" for discharge where the "00060" means discharge  and the "00003" means daily mean value. However, for some gages (at least for the Miami example) there is a lot of variety, adding "Published" or "Published.discharge" at the beginning, for whatever reason. I think I fixed it by renaming the column to discharge in the list before we convert it do a data frame. Then we can drop the remaining columns, leaving only site_no, date, and discharge.

**Comment by rodlammers** [comment]
I think everything is working and I edited to the documentation to note the new output format.
