### ISSUE TITLE
Something to think about-- change `get_flow_data` to make more "tidy"

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#5]
This function would work better in the tidyverse, I think, if we: 
1. Have its first input be a dataframe that includes a column with `site_no`, rather than a vector of site numbers (this would allow us to pipe the output of `gage_extract` or `get_gages` directly into this function)
2. Restructure the output to be a dataframe or tibble instead of a list (this would make it easier to send the output directly into ggplot, to plot with different colors for different stations and so on)

What do you think @rodlammers? Would these changes mess up a lot of other code down the line for you?

**Comment by geanders** [comment]
Also, I'm happy to do this change-- it could be done in a couple of lines of code-- but wanted to see how you think it will impact other code in the package before I did.

**Comment by rodlammers** [comment]
Off the top of my head, I don't think this would mess up any other code. Feel free to go ahead and make that change.
