### ISSUE TITLE
Difference between `get_gages` and `gages_extract`

### ISSUE THREAD

**Issue by geanders** [rodlammers/countyfloods#8]
`get_gages` is usually going to be the preferred function, right? It just removes some gages with all missing data and removes some unneeded columns from `get_gages`, I think. I'm thinking, if that's the case, that all of our examples and tutorial should use `get_gages`, and `gages_extract` is more of a helper function just for us to use within other functions. Is that right?

**Comment by rodlammers** [comment]
Yes, `gages_extract` is just used within `get_gages`. Honestly, when I was writing this I thought the only functions that the user would probably use would be `run_flood` and `map_flood` to do all the analysis at once (and map the results). I think it is good that the other functions are available for the user to potentially customize their own analysis but I think the real focus is on those two functions.

**Comment by geanders** [comment]
Perfect. So, in examples, I'll change any `gages_extract` I find to use `get_gages`, instead, so we won't "promote" `gages_extract` for users (or confuse them with two options that do similar but not exactly the same things).
